using MangosSuperUI.BotLogic.Data;
using MangosSuperUI.BotLogic.Tracking;
using Microsoft.Extensions.Logging;

namespace MangosSuperUI.BotLogic.Core;

/// <summary>
/// The main decision engine. One per bot, owned by BotBrainService.
///
/// TWO TICK CADENCES:
///   - Tactical tick (10-30s): Drives sub-phase progression via CurrentDomain.OnTick().
///     "Have I arrived at the NPC yet?" / "Is my grind task done?" / "Am I stuck?"
///   - Strategic tick (3-10 min): Re-evaluates whether to switch activities entirely.
///     "Should I stop questing and go train?" / "Should I vendor?" / "Am I bored?"
///
/// The tactical tick runs every time BotBrainService calls Tick().
/// The strategic re-evaluation only runs when NextStrategicEval has elapsed.
/// This prevents bots from ADHD-switching activities every 15 seconds while still
/// allowing fast sub-phase progression (arrival detection, kill tracking, etc).
/// </summary>
public class DecisionEngine
{
    private readonly BotIdentity _identity;
    private readonly Dictionary<ActivityType, IBotDomain> _domainMap;
    private readonly LiveStateModifiers _liveState;
    private readonly QuestGraphLoader _questGraph;
    private readonly ILogger _logger;

    private const float ZONE_COMPLETION_GATE = 0.80f; // 80% = don't leave until 80% done

    public IBotDomain CurrentDomain => _domainMap.TryGetValue(_identity.CurrentActivity.Type, out var d)
        ? d
        : _domainMap[ActivityType.Idle];

    public DecisionEngine(
        BotIdentity identity,
        Dictionary<ActivityType, IBotDomain> domainMap,
        LiveStateModifiers liveState,
        QuestGraphLoader questGraph,
        ILogger logger)
    {
        _identity = identity;
        _domainMap = domainMap;
        _liveState = liveState;
        _questGraph = questGraph;
        _logger = logger;

        // First strategic eval should fire immediately — don't make a fresh bot
        // sit idle for 5 minutes. After the first eval, normal scheduling kicks in.
        identity.NextStrategicEval = DateTime.UtcNow;
    }

    /// <summary>
    /// Main decision loop. Called by BotBrainService when this bot's tactical tick fires.
    /// Tactical ticks drive sub-phase work. Strategic re-evaluation (activity switching)
    /// only happens on a much longer cadence.
    ///
    /// IMPORTANT: When a strategic eval fires and the bot STAYS in the current activity,
    /// we return the strategic result directly. RunStrategicEvaluation already called
    /// OnTick() to drive sub-phases — falling through to a second OnTick() call would
    /// see the already-advanced sub-phase and return empty commands, silently discarding
    /// the MOVE_TO/SET_TASK commands generated by the first OnTick's chain loop.
    /// </summary>
    public async Task<DecisionResult> Tick(BotIdentity bot, BotStateSnapshot state)
    {
        var currentActivity = bot.CurrentActivity;
        currentActivity.TicksInState++;

        // 1. Non-interruptible activities (combat, corpse run) — just drive sub-tasks
        if (!currentActivity.IsInterruptible)
        {
            var tickCmds = CurrentDomain.OnTick(bot, state);
            return new DecisionResult
            {
                NewActivity = currentActivity.Type,
                Reason = $"Non-interruptible: {currentActivity.Type}",
                Commands = tickCmds,
                ActivityChanged = false
            };
        }

        // 1.5. PendingAction return stack — cross-domain interruption recovery
        //      If a domain saved a return target (e.g., quest turn-in failed → vendor → resume),
        //      force-return to the saved domain instead of doing a strategic roll.
        if (bot.PendingAction != null && bot.CurrentActivity.Type != bot.PendingAction.ReturnTo)
        {
            var pending = bot.PendingAction;

            // Expire stale PendingActions (> 10 min old)
            if ((DateTime.UtcNow - pending.CreatedAt).TotalMinutes > 10)
            {
                _logger.LogWarning(
                    "[BOT-DECIDE] {Name} PendingAction expired (>10min old), clearing. Was: {Activity} sub-phase={SubPhase}",
                    bot.Name, pending.ReturnTo, pending.SubPhase);
                bot.PendingAction = null;
            }
            // Only return if the current domain is "done" (VendorComplete or similar)
            else if (IsCurrentDomainComplete(bot))
            {
                _logger.LogInformation(
                    "[BOT-DECIDE] {Name} PendingAction: returning to {Activity} sub-phase={SubPhase} quest={Quest}",
                    bot.Name, pending.ReturnTo, pending.SubPhase, pending.QuestId);

                // Switch to the return domain
                bot.PreviousActivity = currentActivity;
                bot.CurrentActivity = new ActivityState
                {
                    Type = pending.ReturnTo,
                    StartedAt = DateTime.UtcNow,
                    SubPhase = pending.SubPhase,
                    IsInterruptible = true
                };

                // Restore quest context if returning to questing
                if (pending.QuestId.HasValue)
                    bot.ActiveQuestId = pending.QuestId;

                // Clear pending action — it's consumed
                bot.PendingAction = null;

                // FLIGHT RECORDER: cross-domain return (e.g., vendoring done → resume turn-in)
                BotTrace.Transition(bot, pending.ReturnTo.ToString(), pending.SubPhase ?? "",
                    "pending_return", detail: $"quest={pending.QuestId}", state: state);
                bot.Story?.Emit(StoryVerb.OVERRIDE, StoryResult.OK,
                    quest: pending.QuestId.HasValue ? new StoryQuest(pending.QuestId.Value) : null,
                    reason: "pending_return",
                    detail: $"→ {pending.ReturnTo}:{pending.SubPhase}");

                // Enter the return domain
                var returnDomain = _domainMap.TryGetValue(pending.ReturnTo, out var rd) ? rd : CurrentDomain;
                var enterCmds = returnDomain.OnEnter(bot, state);

                ScheduleNextStrategicEval(bot);

                return new DecisionResult
                {
                    NewActivity = pending.ReturnTo,
                    Reason = $"PendingAction return: → {pending.ReturnTo} (sub-phase={pending.SubPhase}, quest={pending.QuestId})",
                    Commands = enterCmds,
                    ActivityChanged = true
                };
            }
        }

        // 2. Check if strategic re-evaluation is due
        bool strategicEvalDue = DateTime.UtcNow >= bot.NextStrategicEval;

        // Force strategic eval on critical triggers regardless of timer
        bool criticalTrigger = IsCriticalTrigger(bot, state);

        // ── Session 43: directive compliance at TACTICAL cadence (10-30 s) ──
        // S42 enforced directives only inside strategic evals (3-10 MIN per bot),
        // leaving minutes of legal non-compliance per cycle — not a team. A
        // grouped bot whose activity mismatches its directive now triggers the
        // strategic eval immediately; the enforcement block inside it does the rest.
        if (!strategicEvalDue && !criticalTrigger && !state.IsDead && bot.PendingAction == null)
        {
            var wanted = GetDirectiveActivity(bot);
            if (wanted.HasValue
                && wanted.Value != currentActivity.Type
                && !IsSelfErrand(currentActivity.Type))
            {
                _logger.LogDebug(
                    "[BOT-GROUP] {Name}({Guid}) | directive mismatch ({Cur} → {Want}) — strategic eval forced now",
                    bot.Name, bot.Guid, currentActivity.Type, wanted.Value);
                strategicEvalDue = true;
            }
        }

        // Session 35: Group members are fully autonomous questers — they get their
        // own strategic evals so they can vendor, train, eat independently.
        // The group synchronization happens via gates in QuestingDomain, not by
        // suppressing follower decision-making.

        if (strategicEvalDue || criticalTrigger)
        {
            var strategicResult = await RunStrategicEvaluation(bot, state, currentActivity, criticalTrigger);

            // Always reschedule — whether we switched or stayed.
            // Previously this only ran on the "stay" path, so after an activity switch
            // NextStrategicEval stayed at the constructor's UtcNow value (in the past),
            // causing the strategic eval to fire again on the very next tick.
            ScheduleNextStrategicEval(bot);

            // Return the strategic result directly. It already contains the right
            // commands — either OnEnter (activity changed) or OnTick (staying).
            return strategicResult;
        }

        // 3. Tactical tick only — no strategic eval this tick.
        //    Drive sub-phase progression in current domain.
        var commands = CurrentDomain.OnTick(bot, state);
        return new DecisionResult
        {
            NewActivity = currentActivity.Type,
            Reason = $"Tactical tick: {currentActivity.Type} (sub-phase driving, tick #{currentActivity.TicksInState})",
            Commands = commands,
            ActivityChanged = false
        };
    }

    /// <summary>
    /// The full strategic evaluation: get weights, apply modifiers, roll, maybe switch.
    /// This is the expensive path that only fires every 3-10 minutes.
    /// </summary>
    private async Task<DecisionResult> RunStrategicEvaluation(
        BotIdentity bot, BotStateSnapshot state, ActivityState currentActivity, bool wasCritical)
    {
        // Session 29: Increment training tick counter so the hard override
        // at tick 10 (weight=15.0) can eventually fire. Without this,
        // TicksSinceLastTrained stays at 0 forever and the override never triggers.
        if (bot.HasUnlearnedSpells)
            bot.TicksSinceLastTrained++;

        bot.Story?.Emit(StoryVerb.EVAL, StoryResult.START,
            reason: wasCritical ? "critical" : "strategic",
            detail: $"in {currentActivity.Type} {currentActivity.MinutesInState:F1}min");
        var weights = CurrentDomain.EvaluateTransitions(bot, state);

        ApplyPersonalityModifiers(weights, bot.Personality);

        var liveMods = await _liveState.GetModifiers(bot, state);
        ApplyLiveModifiers(weights, liveMods);

        ApplyBoredomEscalation(weights, bot, currentActivity);

        foreach (var quirk in bot.Personality.Quirks)
            quirk.ApplyModifiers(weights, bot);

        // Zero out weights for non-operational domains.
        // Stub domains (IsOperational = false) should never win a roll — the bot
        // would switch in, do nothing (no commands), and immediately trigger a
        // critical eval because it's idle, causing a cascade of pointless switches.
        FilterNonOperationalDomains(weights, currentActivity.Type);

        // --- Session 9: Hard overrides before roll ---

        // Dead bot: force CorpseRunning. No domain emits CorpseRunning weights
        // (death isn't a "transition" — it's an emergency). Skip the weighted roll entirely.
        if (state.IsDead)
        {
            weights.Clear();
            weights[ActivityType.CorpseRunning] = 100.0f;
            bot.Story?.Emit(StoryVerb.OVERRIDE, StoryResult.OK,
                reason: "dead", detail: "→ CorpseRunning (survival)");
        }

        // AuctionHouse is a stub — no OnTick, no sub-phases, no commands.
        // Bots roll in and idle for 20+ ticks until boredom pushes them out.
        // Remove until AuctionHouse is actually implemented.
        weights.Remove(ActivityType.AuctionHouse);

        // Don't vendor with nearly-empty bags — nothing to sell.
        // usedSlots <= 4 catches fresh bots with only starting gear/quest items.
        if (weights.ContainsKey(ActivityType.Vendoring))
        {
            uint usedSlots = state.TotalSlots - state.FreeSlots;
            if (usedSlots <= 4)
                weights[ActivityType.Vendoring] = 0f;
        }

        // Training override: if bot has unlearned spells and has been ignoring
        // training for 10+ ticks (~2-5 min), force the training weight high enough
        // to win. Without this, training weight (0.04 base × 2.0 LiveMod = 0.08)
        // can never beat Questing (8-12) and bots never train.
        if (bot.HasUnlearnedSpells && bot.TicksSinceLastTrained >= 10
            && bot.CurrentActivity.Type != ActivityType.TravelingToTrainer
            && bot.CurrentActivity.Type != ActivityType.Training)
        {
            weights[ActivityType.TravelingToTrainer] = 15.0f;
            bot.Story?.Emit(StoryVerb.OVERRIDE, StoryResult.OK,
                reason: "training_overdue",
                detail: $"→ TravelingToTrainer (idle {bot.TicksSinceLastTrained} ticks)");
        }

        // ── Session 42: GroupCoordinator directive enforcement (ARCH §7a) ──
        // Grouped bots obey the group directive unless an individual hard need
        // (bags full / low HP / overdue training) wins, they're mid-errand (let
        // the errand finish — the directive re-applies next eval), or a
        // PendingAction return is staged. Solo bots and stale directives (>2 min:
        // disband/restart guard) fall through to the normal roll untouched.
        // Computed in BotBrainService, ENFORCED here, EXECUTED by domains —
        // never decided inside a domain (the gotcha-96 trap).
        bool directiveForced = false;
        var directiveActivity = GetDirectiveActivity(bot);   // Session 43: followers → Following
        if (!state.IsDead
            && directiveActivity.HasValue
            && !IsSelfErrand(currentActivity.Type)
            && bot.PendingAction == null)
        {
            // Session 44b: maintenance is the GROUP's business now, not the
            // member's. Bags-full and overdue training used to let a member peel
            // off solo while the rest held — exactly the "each member its own
            // mind" noise the coordinator exists to kill. Both are detected by
            // the BotBrainService macro brain, which routes the WHOLE formation
            // to the service NPC (GroupErrand directive) and fires the service
            // interacts itself. The only per-member override left is survival:
            // critically low HP → eat IN PLACE (MaintenanceDomain doesn't move),
            // and death is handled by the hard CorpseRunning override above.
            bool individualNeed = state.HealthPercent < 0.35f;

            if (!individualNeed)
            {
                weights.Clear();
                // Session 43 formation model: followers get Following (C++ MoveFollow
                // glue, 6 yd, combat-interruptible, opportunistic quest interact);
                // the leader gets Questing or Grinding-at-anchor per the directive.
                weights[directiveActivity.Value] = 100.0f;
                directiveForced = true;
                bot.Story?.Emit(StoryVerb.DIRECTIVE, StoryResult.OK,
                    target: new StoryTarget(bot.GroupAnchorX, bot.GroupAnchorY, bot.GroupAnchorZ, bot.GroupAnchorMap),
                    reason: bot.GroupDirective.ToString(),
                    detail: $"→ {directiveActivity.Value}");
                _logger.LogDebug(
                    "[BOT-GROUP] {Name}({Guid}) | directive {Directive} enforced (anchor {AX:F0},{AY:F0})",
                    bot.Name, bot.Guid, bot.GroupDirective, bot.GroupAnchorX, bot.GroupAnchorY);
            }
        }

        var (selectedActivity, rollValue) = WeightedRoller.Roll(weights);
        bot.Story?.Emit(StoryVerb.ROLL, StoryResult.OK,
            reason: selectedActivity == currentActivity.Type ? "stay" : $"→{selectedActivity}",
            detail: $"roll={rollValue:F2} | " + string.Join(" ",
                weights.Where(w => w.Value > 0.001f).OrderByDescending(w => w.Value).Take(5)
                       .Select(w => $"{w.Key}={w.Value:F2}")));

        // ── Session 29: Zone completion gate ──
        // If a "wandering" activity (Exploring, Grinding, Idle) won the roll and
        // would pull the bot away from questing, check: does the current zone still
        // have >20% of its quests unfinished? If yes, override back to Questing.
        // Vendoring, Training, Eating, CorpseRunning are ERRANDS — always allowed.
        // Only Questing can decide to move zones (when it runs out of local quests).
        // Session 42: a directive-forced pick is exempt — the zone gate would flip
        // a forced HoldAndGrind/Regroup (Grinding) straight back to Questing.
        if (selectedActivity != currentActivity.Type && _questGraph.IsLoaded && !directiveForced)
        {
            bool isZoneExitActivity =
                selectedActivity == ActivityType.Exploring ||
                selectedActivity == ActivityType.Grinding ||
                selectedActivity == ActivityType.Idle;

            if (isZoneExitActivity && state.ZoneId > 0)
            {
                float completionRatio = GetZoneCompletionRatio(bot, state.ZoneId);
                if (completionRatio < ZONE_COMPLETION_GATE)
                {
                    _logger.LogInformation(
                        "[BOT-ZONE] {Name}({Guid}) | ZONE GATE: blocked {Activity} — " +
                        "zone {Zone} only {Pct:P0} complete (need {Gate:P0}), staying in Questing",
                        bot.Name, bot.Guid, selectedActivity,
                        state.ZoneId, completionRatio, ZONE_COMPLETION_GATE);

                    bot.Story?.Emit(StoryVerb.OVERRIDE, StoryResult.BLOCK,
                        reason: "zone_gate",
                        detail: $"blocked {selectedActivity} — zone {state.ZoneId} {completionRatio:P0} < {ZONE_COMPLETION_GATE:P0} → Questing");
                    selectedActivity = ActivityType.Questing;
                }
            }
        }

        // Record transition for stuck detection
        bot.StuckDetector.RecordTransition(selectedActivity.ToString());

        var stuckReport = bot.StuckDetector.Check();
        if (stuckReport != null)
        {
            _logger.LogWarning(
                "[BOT-STUCK] {Name}: {Type} detected — pattern={Pattern} " +
                "occurrences={Occ} window={Win}",
                bot.Name, stuckReport.Type, stuckReport.Pattern,
                stuckReport.Occurrences, stuckReport.Window);

            // FLIGHT RECORDER: pattern-loop signal (complements the recorder's
            // ownership-freeze sweep — this catches activity ping-ponging).
            BotTrace.Mark(bot,
                $"stuck-detector {stuckReport.Type}: {stuckReport.Pattern} x{stuckReport.Occurrences}",
                state);
            bot.Story?.Wedge(stuckReport.Type,
                $"{stuckReport.Pattern} x{stuckReport.Occurrences} in {stuckReport.Window.TotalMinutes:F0}min");

            // Emit SignalR for dashboard visibility
            // (use existing BotDecision emit pattern)

            // Optional: force a wander/idle cooldown to break the loop
            // result.ForceActivity = ActivityType.Exploring;
            // bot.NextStrategicEval = DateTime.UtcNow.AddMinutes(2);
        }

        var result = new DecisionResult
        {
            NewActivity = selectedActivity,
            WeightBreakdown = new Dictionary<ActivityType, float>(weights),
            RollValue = rollValue,
            ActivityChanged = selectedActivity != currentActivity.Type
        };

        // FLIGHT RECORDER: the brain's actual decision — full weight vector, winner, roll.
        BotTrace.Decision(bot, result, wasCritical ? "critical" : "strategic", state);

        // ── DIAGNOSTIC: Strategic eval weight breakdown ──
        var topWeights = weights
            .Where(w => w.Value > 0.001f)
            .OrderByDescending(w => w.Value)
            .Take(5)
            .Select(w => $"{w.Key}={w.Value:F2}");
        _logger.LogInformation(
            "[BOT-STRAT] {Name}({Guid}) | {Action} {Current} (roll={Roll:F2}{Crit}) | Weights: {Weights} | InActivity={Minutes:F1}min",
            bot.Name, bot.Guid,
            selectedActivity == currentActivity.Type ? "STAY" : $"SWITCH→{selectedActivity}",
            currentActivity.Type,
            rollValue,
            wasCritical ? ", CRITICAL" : "",
            string.Join(" ", topWeights),
            currentActivity.MinutesInState);

        if (result.ActivityChanged)
        {
            bot.PreviousActivity = currentActivity;

            // Auto-save PendingAction when entering Vendoring so the bot returns
            // to what it was doing. Don't overwrite an existing PendingAction
            // (e.g., QuestingDomain already set one on bags-full turn-in failure).
            //
            // Session 9 fix: Don't save a PendingAction to return to another
            // EconomyDomain activity (AuctionHouse, TravelingToVendor). These are
            // owned by the same domain — returning to them creates a ping-pong loop
            // where Vendoring completes → PendingAction returns to AuctionHouse →
            // AuctionHouse is a stub → immediately re-rolls into Vendoring → repeat.
            // Only save PendingActions for activities owned by DIFFERENT domains.
            if (selectedActivity == ActivityType.Vendoring && bot.PendingAction == null)
            {
                bool sameOwnerDomain =
                    currentActivity.Type == ActivityType.AuctionHouse ||
                    currentActivity.Type == ActivityType.TravelingToVendor ||
                    currentActivity.Type == ActivityType.Vendoring;

                if (!sameOwnerDomain)
                {
                    bot.PendingAction = new PendingAction
                    {
                        ReturnTo = currentActivity.Type,
                        SubPhase = currentActivity.SubPhase ?? "",
                        QuestId = bot.ActiveQuestId
                    };
                    _logger.LogInformation(
                        "[BOT-DECIDE] {Name} auto-saved PendingAction: return to {Activity} sub-phase={Sub} quest={Quest}",
                        bot.Name, currentActivity.Type, currentActivity.SubPhase, bot.ActiveQuestId);
                }
                else
                {
                    _logger.LogInformation(
                        "[BOT-DECIDE] {Name} skipping PendingAction save — switching from {From} to Vendoring (same domain)",
                        bot.Name, currentActivity.Type);
                }
            }

            bot.CurrentActivity = new ActivityState
            {
                Type = selectedActivity,
                StartedAt = DateTime.UtcNow,
                IsInterruptible = selectedActivity != ActivityType.CorpseRunning
            };

            // FLIGHT RECORDER: strategic activity switch (the domain's OnEnter below
            // will emit its own sub-phase transition once Batch 3 instruments it).
            BotTrace.Transition(bot, currentActivity.Type.ToString(), selectedActivity.ToString(),
                wasCritical ? "critical_switch" : "strategic_switch",
                detail: $"roll={rollValue:F2}", state: state);

            if (_domainMap.TryGetValue(selectedActivity, out var newDomain))
            {
                result.Commands = newDomain.OnEnter(bot, state);
            }
            result.Reason = $"Strategic switch: {currentActivity.Type} → {selectedActivity} " +
                            $"(roll: {rollValue:F2}{(wasCritical ? ", critical trigger" : "")})";
        }
        else
        {
            result.Commands = CurrentDomain.OnTick(bot, state);
            result.Reason = $"Strategic eval: staying in {currentActivity.Type} " +
                            $"(next eval in {GetStrategicIntervalMinutes(bot):F1}min)";
        }

        return result;
    }

    // ── Session 42: GroupCoordinator (ARCH §7a) ─────────────────────────
    /// <summary>
    /// True when the activity is a self-maintenance errand the group directive
    /// must not interrupt (let it finish; the directive re-applies next eval).
    /// Mirrors BotBrainService.IsAwayOnErrand — keep the two sets identical.
    /// </summary>
    private static bool IsSelfErrand(ActivityType a)
    {
        return a == ActivityType.Vendoring
            || a == ActivityType.TravelingToVendor   // Session 43: real enum value, missed in S42
            || a == ActivityType.Training
            || a == ActivityType.TravelingToTrainer
            || a == ActivityType.Eating
            || a == ActivityType.CorpseRunning
            || a == ActivityType.FlightPath;         // Session 43: on a taxi = away
    }

    // ── Session 43: directive → activity mapping (formation model) ──────
    /// <summary>
    /// What activity the group directive demands of THIS bot right now, or null
    /// when no fresh directive applies (solo, disbanded, stale >2 min).
    /// Formation rule: FOLLOWERS ALWAYS FOLLOW — the leader is the group's only
    /// quest-pathing agent. Followers stay glued via C++ MoveFollow (FollowDomain)
    /// regardless of directive flavor; the leader maps Questing→Questing and
    /// HoldAndGrind/Regroup→Grinding-at-anchor (CombatDomain, Session 42).
    /// </summary>
    private static ActivityType? GetDirectiveActivity(BotIdentity bot)
    {
        if (!bot.IsGrouped || bot.GroupDirective == GroupDirective.None)
            return null;
        if ((DateTime.UtcNow - bot.GroupDirectiveUtc).TotalSeconds >= 120)
            return null;
        if (bot.IsGroupFollower)
            return ActivityType.Following;
        return bot.GroupDirective == GroupDirective.Questing
            ? ActivityType.Questing
            : ActivityType.Grinding;
    }

    /// <summary>
    /// Zero out weights for any activity whose domain is not operational.
    /// The current activity is never filtered — if the bot is somehow already in
    /// a non-operational domain, it needs to be able to "stay" so that boredom
    /// escalation can eventually push it out naturally.
    /// </summary>
    private void FilterNonOperationalDomains(Dictionary<ActivityType, float> weights, ActivityType current)
    {
        foreach (var activity in weights.Keys.ToList())
        {
            if (activity == current) continue;

            if (_domainMap.TryGetValue(activity, out var domain))
            {
                if (!domain.IsOperational)
                    weights[activity] = 0f;
            }
            else
            {
                // No domain registered for this activity — can't go there
                weights[activity] = 0f;
            }
        }
    }

    /// <summary>
    /// Critical triggers that force an immediate strategic eval regardless of timer.
    /// These are "the world changed significantly" moments.
    ///
    /// IMPORTANT: These must be rare, genuine emergencies. If a critical trigger fires
    /// every tick (e.g., "bot is Idle"), it causes a cascade of strategic evals that
    /// bounce the bot between stub domains. The Idle case is handled differently:
    /// NextStrategicEval starts at UtcNow so the first eval is immediate, and the
    /// non-operational filter prevents landing in stubs.
    /// </summary>
    private bool IsCriticalTrigger(BotIdentity bot, BotStateSnapshot state)
    {
        // Just died — need to reconsider what we're doing
        if (state.IsDead && bot.CurrentActivity.Type != ActivityType.CorpseRunning)
            return true;

        // Just leveled up — training pressure (only fires once per level-up)
        if (bot.HasUnlearnedSpells && bot.TicksSinceLastTrained == 0)
            return true;

        // HP critical while not eating — survival override
        if (state.HealthPercent < 0.25f && bot.CurrentActivity.Type != ActivityType.Eating)
            return true;

        // Bags completely full and not already vendoring — need to sell.
        // Session 44b: grouped bots with a fresh directive are exempt — the
        // GroupErrand macro brain detects bags-full at the group level, and the
        // enforcement block would hold them in formation anyway, so firing this
        // every tick would just storm strategic evals for the errand's duration.
        if (state.FreeSlots == 0 && bot.CurrentActivity.Type != ActivityType.Vendoring
            && GetDirectiveActivity(bot) == null)
            return true;

        // Bot stuck in a non-operational domain — escape immediately.
        // This happens if a bot was in a domain that got flagged non-operational
        // between sessions, or if something went wrong. Force one strategic eval
        // to get it out, then normal scheduling takes over.
        if (!CurrentDomain.IsOperational && bot.CurrentActivity.TicksInState == 1)
            return true;

        return false;
    }

    /// <summary>
    /// Schedule the next strategic re-evaluation.
    /// Base: 3-10 minutes, personality-modulated.
    /// Patient, efficient bots = longer intervals (commit harder).
    /// Spontaneous, indecisive bots = shorter intervals (reconsider more).
    /// </summary>
    private void ScheduleNextStrategicEval(BotIdentity bot)
    {
        float baseMinutes = GetStrategicIntervalMinutes(bot);
        float jitter = WeightedRoller.Range(0.75f, 1.25f);
        float minutes = baseMinutes * jitter;
        bot.NextStrategicEval = DateTime.UtcNow.AddMinutes(minutes);
    }

    /// <summary>
    /// Calculate the strategic eval interval in minutes based on personality.
    /// Range: 3 min (ADHD bot) to 10 min (patient, focused bot).
    /// </summary>
    private float GetStrategicIntervalMinutes(BotIdentity bot)
    {
        var p = bot.Personality;

        float minutes = 5.0f;
        minutes += Lerp(-1.0f, 3.0f, p.Patience);
        minutes += Lerp(-0.5f, 1.5f, p.Efficiency);
        minutes += Lerp(0.5f, -2.0f, p.Spontaneity);
        minutes += Lerp(0.0f, -1.0f, p.Indecisiveness);

        if (p.Quirks.Any(q => q.Id == "SpeedDemon"))
            minutes *= 0.6f;

        return Math.Clamp(minutes, 3.0f, 10.0f);
    }

    private void ApplyPersonalityModifiers(Dictionary<ActivityType, float> weights, BotPersonality p)
    {
        ModWeight(weights, ActivityType.Questing, Lerp(0.6f, 1.4f, p.Patience));
        ModWeight(weights, ActivityType.Questing, Lerp(0.8f, 1.5f, p.Efficiency));
        ModWeight(weights, ActivityType.Grinding, Lerp(0.7f, 1.3f, p.Patience));
        ModWeight(weights, ActivityType.Grinding, Lerp(0.7f, 1.4f, p.Aggression));
        ModWeight(weights, ActivityType.Vendoring, Lerp(0.5f, 1.5f, p.Greed));
        ModWeight(weights, ActivityType.AuctionHouse, Lerp(0.3f, 2.0f, p.Greed));
        ModWeight(weights, ActivityType.Exploring, Lerp(0.3f, 2.0f, p.Curiosity));
        ModWeight(weights, ActivityType.Exploring, Lerp(1.0f, 0.3f, p.Efficiency));
        ModWeight(weights, ActivityType.Socializing, Lerp(0.2f, 2.5f, p.Sociability));
        ModWeight(weights, ActivityType.Socializing, Lerp(1.0f, 0.3f, p.Efficiency));
        ModWeight(weights, ActivityType.Eating, Lerp(0.8f, 1.3f, p.Cautiousness));

        float spontBonus = p.Spontaneity * 0.15f;
        var current = _identity.CurrentActivity.Type;
        foreach (var key in weights.Keys.ToList())
            if (key != current) weights[key] += spontBonus;
    }

    private void ApplyLiveModifiers(Dictionary<ActivityType, float> weights, LiveModifierSet mods)
    {
        ModWeight(weights, ActivityType.Questing, mods.QuestWeight);
        ModWeight(weights, ActivityType.Grinding, mods.GrindWeight);
        ModWeight(weights, ActivityType.Vendoring, mods.VendorWeight);
        ModWeight(weights, ActivityType.AuctionHouse, mods.AHBuyWeight);
        ModWeight(weights, ActivityType.Socializing, mods.SocialWeight);
        ModWeight(weights, ActivityType.Exploring, mods.ExploreWeight);
        ModWeight(weights, ActivityType.TravelingToTrainer, mods.TrainingWeight);
    }

    private void ApplyBoredomEscalation(
        Dictionary<ActivityType, float> weights, BotIdentity bot, ActivityState activity)
    {
        // Boredom is calibrated for the longer strategic intervals.
        // With 3-10 min between evals, a rate of 0.04/min means the stay weight
        // halves after ~12 minutes for an impatient bot, ~25 min for a patient one.
        float boredomRate = Lerp(0.04f, 0.012f, bot.Personality.Patience);
        float minutesIn = (float)activity.MinutesInState;
        float boredomPenalty = 1.0f - (minutesIn * boredomRate);
        boredomPenalty = Math.Max(0.15f, boredomPenalty);

        if (weights.ContainsKey(activity.Type))
            weights[activity.Type] *= boredomPenalty;
    }

    private static void ModWeight(Dictionary<ActivityType, float> w, ActivityType t, float multiplier)
    {
        if (w.ContainsKey(t)) w[t] *= multiplier;
    }

    private static float Lerp(float min, float max, float t) => min + (max - min) * t;

    /// <summary>
    /// Check if the current domain has finished its work (for PendingAction return decisions).
    /// We only return to a PendingAction target when the interrupting domain is "done."
    /// </summary>
    private bool IsCurrentDomainComplete(BotIdentity bot)
    {
        var subPhase = bot.CurrentActivity.SubPhase ?? "";
        return bot.CurrentActivity.Type switch
        {
            ActivityType.Vendoring => subPhase == "VendorComplete" || subPhase == "Done" || subPhase == "",
            ActivityType.Eating => subPhase == "Done" || subPhase == "",
            _ => subPhase == "" || subPhase == "Done" || subPhase == "Complete"
        };
    }

    /// <summary>
    /// Session 29: Calculate what fraction of the bot's current zone quests are completed.
    /// Uses QuestGraphLoader.GetAvailableQuests (which filters by race/class/level/prereqs)
    /// to count remaining zone quests, plus CompletedQuestIds to count finished ones.
    /// Returns 0.0 (nothing done) to 1.0 (zone fully cleared).
    /// </summary>
    private float GetZoneCompletionRatio(BotIdentity bot, int zoneId)
    {
        int raceBit = QuestGraphLoader.RaceToBitmask(bot.Race);
        int classBit = QuestGraphLoader.ClassToBitmask(bot.ClassId);

        // Get all quests the bot COULD do (filters prereqs, race, class, level)
        var available = _questGraph.GetAvailableQuests(raceBit, classBit, bot.Level,
            bot.CompletedQuestIds, null);

        // Count how many zone quests are still available (not yet completed)
        int remainingInZone = available.Count(q => q.ZoneId == zoneId);

        // Count how many zone quests the bot has already completed
        int completedInZone = 0;
        foreach (var questId in bot.CompletedQuestIds)
        {
            var node = _questGraph.GetQuest(questId);
            if (node != null && node.ZoneId == zoneId)
                completedInZone++;
        }

        int totalZoneQuests = remainingInZone + completedInZone;
        if (totalZoneQuests == 0)
            return 1.0f; // no quests for this zone = "done"

        return (float)completedInZone / totalZoneQuests;
    }
}