using System.Text.Json;

namespace MangosSuperUI.Services.WeaponForge;

/// <summary>
/// A SHIPPED later-expansion item catalog: entry → name / class / subclass / display id / quality /
/// basic stats for every class-2 weapon AND class-4 armor/shield in an open-source world database,
/// baked into <c>wwwroot/data/*.json</c> at development time:
///
///   • <see cref="TbcItemCatalog"/>   — <c>tbc-item-catalog.json</c>, cmangos tbc-db (2.4.3 / 8606)
///   • <see cref="WotlkItemCatalog"/> — <c>wotlk-item-catalog.json</c>, azerothcore-wotlk
///     <c>data/sql/base/db_world/item_template.sql</c> (3.3.5a / 12340); generated by a one-off
///     script that parses the INSERT tuples (30,229 rows: 6,651 weapons + 23,578 armor/shields).
///
/// Item names never exist in the client MPQs (the client learns them from the server's item
/// query), so without this file a browse could only show model stems. Shipping the list means any
/// SuperUI user gets real item names with nothing but their own later-client files — no live
/// TBC/WotLK database required. Armor and shields ride along for the Armor Forge; both files share
/// one 13-field layout so one loader serves both.
///
/// The runtime join is: catalog item.displayId → the user's own mounted ItemDisplayInfo row
/// (<see cref="LegacyMpqSource.WeaponIndex"/>) → model + texture members. The catalog also maps each
/// weapon subclass onto a Forge weapon-type profile so the import pre-selects the right family.
/// Loaded lazily once; a missing/corrupt file degrades to the model-stem browse, never an error.
/// </summary>
public abstract class LegacyItemCatalog
{
    private readonly IWebHostEnvironment _env;
    private readonly ILogger _logger;
    private readonly object _lock = new();
    private IReadOnlyList<LegacyItemInfo>? _items;
    private Dictionary<uint, List<LegacyItemInfo>>? _byDisplay;

    protected LegacyItemCatalog(IWebHostEnvironment env, ILogger logger, string catalogWebPath, string label)
    {
        _env = env;
        _logger = logger;
        CatalogWebPath = catalogWebPath;
        Label = label;
    }

    /// <summary>Web-root relative JSON path, e.g. <c>data/tbc-item-catalog.json</c>.</summary>
    public string CatalogWebPath { get; }
    public string Label { get; }

    public IReadOnlyList<LegacyItemInfo> Items
    {
        get
        {
            if (_items is not null) return _items;
            lock (_lock)
            {
                _items ??= Load();
                return _items;
            }
        }
    }

    /// <summary>Items grouped by their display id, for the join against the mounted archives.</summary>
    public IReadOnlyDictionary<uint, List<LegacyItemInfo>> ByDisplayId
    {
        get
        {
            if (_byDisplay is not null) return _byDisplay;
            lock (_lock)
            {
                if (_byDisplay is null)
                {
                    var map = new Dictionary<uint, List<LegacyItemInfo>>();
                    foreach (var item in Items)
                    {
                        if (!map.TryGetValue(item.DisplayId, out var list))
                            map[item.DisplayId] = list = new List<LegacyItemInfo>();
                        list.Add(item);
                    }
                    _byDisplay = map;
                }
                return _byDisplay;
            }
        }
    }

    public LegacyItemInfo? FindByEntry(uint entry) => Items.FirstOrDefault(i => i.Entry == entry);

    private IReadOnlyList<LegacyItemInfo> Load()
    {
        var path = Path.Combine(_env.WebRootPath, CatalogWebPath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path))
        {
            _logger.LogWarning("{Label} item catalog: {Path} not found — browse falls back to model stems", Label, path);
            return Array.Empty<LegacyItemInfo>();
        }

        try
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            var items = new List<LegacyItemInfo>();
            foreach (var row in doc.RootElement.GetProperty("items").EnumerateArray())
            {
                // fields: entry, name, class, subclass, displayId, quality, inventoryType,
                //         itemLevel, requiredLevel, delayMs, dmgMin, dmgMax, sheath
                //         [, setId] — optional trailing item_template.itemset (WotLK catalog only;
                //         seasonal/tier variants are linked to their set on the ITEM, not in ItemSet.dbc)
                items.Add(new LegacyItemInfo
                {
                    Entry = row[0].GetUInt32(),
                    Name = row[1].GetString() ?? "",
                    ItemClass = row[2].GetInt32(),
                    Subclass = row[3].GetInt32(),
                    DisplayId = row[4].GetUInt32(),
                    Quality = row[5].GetInt32(),
                    InventoryType = row[6].GetInt32(),
                    ItemLevel = row[7].GetInt32(),
                    RequiredLevel = row[8].GetInt32(),
                    DelayMs = row[9].GetInt32(),
                    DmgMin = row[10].GetSingle(),
                    DmgMax = row[11].GetSingle(),
                    Sheath = row[12].GetInt32(),
                    SetId = row.GetArrayLength() > 13 ? row[13].GetUInt32() : 0,
                });
            }
            _logger.LogInformation("{Label} item catalog: loaded {Count} items (weapons + armor/shields) from {Path}", Label, items.Count, CatalogWebPath);
            return items;
        }
        catch (Exception ex)
        {
            _logger.LogWarning("{Label} item catalog: could not read {Path}: {Err} — browse falls back to model stems",
                Label, path, ex.Message);
            return Array.Empty<LegacyItemInfo>();
        }
    }

    /// <summary>Class-2 subclass → Forge weapon-family key (identical enum in 2.4.3 and 3.3.5a).
    /// Ranged subclasses map onto the ranged families (the import is rigid on the family scaffold's
    /// root bone — a bow's limb draw animation is not carried, its projectile visual and slot are).
    /// Subclasses the pipeline cannot represent (fist weapons pair two models; fishing poles) return
    /// null and are excluded from the browse.</summary>
    public static string? TypeKeyFor(int itemClass, int subclass) => itemClass switch
    {
        2 => TypeKeyForSubclass(subclass),
        4 when subclass == 6 => "shield",   // armor class, shield subclass — the Shield family
        _ => null,
    };

    public static string? TypeKeyForSubclass(int subclass) => subclass switch
    {
        0 => "axe1h",
        1 => "axe2h",
        2 => "bow",
        3 => "gun",
        4 => "mace1h",
        5 => "mace2h",
        6 => "polearm",
        7 => "sword1h",
        8 => "sword2h",
        10 => "staff",
        14 => "sword1h",   // Miscellaneous (brooms etc.) — closest static 1H contract
        15 => "dagger",
        16 => "thrown",
        18 => "crossbow",
        19 => "wand",
        _ => null,
    };
}
/// <summary>One mounted later client + its shipped catalog — everything an import lane needs to
/// browse and extract. Resolved by key ("tbc" / "wotlk") through <see cref="LegacyImportSources"/>.</summary>
public sealed class LegacyImportSource
{
    public LegacyImportSource(LegacyMpqSource mpq, LegacyItemCatalog items)
    {
        Mpq = mpq;
        Items = items;
    }

    public string Key => Mpq.Key;
    public string Label => Mpq.Label;
    public LegacyMpqSource Mpq { get; }
    public LegacyItemCatalog Items { get; }
}

/// <summary>Registry of the import lanes the Forges expose: TBC and WotLK. Add a lane here and
/// the weapon/armor controllers, status endpoints and UI cards pick it up by key.</summary>
public sealed class LegacyImportSources
{
    public LegacyImportSources(TbcMpqSource tbcMpq, TbcItemCatalog tbcItems, WotlkMpqSource wotlkMpq, WotlkItemCatalog wotlkItems)
    {
        Tbc = new LegacyImportSource(tbcMpq, tbcItems);
        Wotlk = new LegacyImportSource(wotlkMpq, wotlkItems);
        All = new[] { Tbc, Wotlk };
    }

    public LegacyImportSource Tbc { get; }
    public LegacyImportSource Wotlk { get; }
    public IReadOnlyList<LegacyImportSource> All { get; }

    /// <summary>Lane by key; unknown/blank keys fall back to TBC (the original lane).</summary>
    public LegacyImportSource Get(string? key) =>
        string.Equals(key, WotlkMpqSource.SourceKey, StringComparison.OrdinalIgnoreCase) ? Wotlk : Tbc;

    public bool IsKnown(string? key) =>
        string.Equals(key, TbcMpqSource.SourceKey, StringComparison.OrdinalIgnoreCase) ||
        string.Equals(key, WotlkMpqSource.SourceKey, StringComparison.OrdinalIgnoreCase);
}

/// <summary>One shipped later-expansion item (from the open-source world DB). Class 2 = weapon,
/// class 4 = armor (subclass 6 = shield). Lane-neutral: TBC and WotLK rows use
/// the same shape.</summary>
public sealed record LegacyItemInfo
{
    public required uint Entry { get; init; }
    public required string Name { get; init; }
    public required int ItemClass { get; init; }
    public required uint DisplayId { get; init; }
    public required int Quality { get; init; }
    public required int Subclass { get; init; }
    public required int InventoryType { get; init; }
    public required int ItemLevel { get; init; }
    public required int RequiredLevel { get; init; }
    public required int DelayMs { get; init; }
    public required float DmgMin { get; init; }
    public required float DmgMax { get; init; }
    public required int Sheath { get; init; }
    /// <summary>item_template.itemset, or 0. Only the WotLK catalog carries it — from 3.3.5a on,
    /// later arena seasons and higher-ilvl tier versions are set members through this column while
    /// ItemSet.dbc's itemID[17] lists only the base variant.</summary>
    public uint SetId { get; init; }
}
