using System.Buffers.Binary;
using SkiaSharp;

namespace MangosSuperUI.Services.WeaponForge;

/// <summary>
/// The pure compiler boundary (WEAPON_GEN.md §4.1): RigidWeaponMesh + WeaponTexture + options →
/// M2 bytes, BLP bytes, preview GLB, diagnostics. It has no live DB/RA/client-path dependency. The
/// mesh→M2 serialization step is delegated to <see cref="IWeaponMeshWriter"/> — absent until the
/// Phase-3 donor-scaffold writer exists, at which point it drops in without touching this class.
/// Phase 1 (the golden donor clone) does not use this compiler; it packages donor bytes directly.
/// </summary>
public sealed class WeaponAssetCompiler
{
    private readonly IWeaponMeshWriter _writer;
    private readonly BlpWriterService _blp;
    private readonly WeaponPreviewService _preview;
    private readonly ILogger<WeaponAssetCompiler> _logger;

    public WeaponAssetCompiler(IWeaponMeshWriter writer, BlpWriterService blp,
        WeaponPreviewService preview, ILogger<WeaponAssetCompiler> logger)
    {
        _writer = writer;
        _blp = blp;
        _preview = preview;
        _logger = logger;
    }

    public WeaponCompileOutput Compile(RigidWeaponMesh mesh, WeaponTexture? texture, WeaponCompileOptions options)
    {
        var diag = new ForgeDiagnostics("compile");

        int effectTextureCount = options.EffectTextures?.Count ?? 0;
        int effectPathCount = options.EffectTexturePaths?.Count ?? 0;
        if (effectTextureCount != effectPathCount)
            diag.Error("texture.effect.parallel",
                $"Effect texture count {effectTextureCount} does not match effect path count {effectPathCount}.");
        if (options.EffectTexturePaths is { Count: > 0 } effectPaths)
        {
            var uniquePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < effectPaths.Count; i++)
            {
                string? path = effectPaths[i];
                if (string.IsNullOrWhiteSpace(path))
                    diag.Error("texture.effect.path", $"Effect texture path {i + 1} is empty.");
                else if (!uniquePaths.Add(path))
                    diag.Error("texture.effect.path", $"Effect texture path '{path}' is duplicated.");
            }
        }

        // 1) Input mesh validation (§7.1).
        var meshDiag = RigidWeaponMeshValidator.Validate(mesh, options.MeshValidation);
        diag.AddRange(meshDiag);

        // 2) Texture → BLP (§2.4). Independent of mesh validity so a texture problem is
        //    reported even when geometry is rejected. Effect textures (multi-pass glow) encode
        //    alongside — packaged as Type-0 members next to the model.
        byte[]? blp = null;
        if (texture is not null)
            blp = EncodeTexture(texture, diag);

        var effectBlps = new List<byte[]>();
        if (options.EffectTextures is { Count: > 0 })
        {
            for (int i = 0; i < options.EffectTextures.Count; i++)
            {
                var enc = EncodeTexture(options.EffectTextures[i], diag);
                if (enc is null)
                {
                    diag.Error("blp.effect", $"Effect texture {i + 1} failed to encode.");
                    break;
                }
                effectBlps.Add(enc);
            }
        }

        // 3) Mesh → M2, only if the mesh passed and a writer is available.
        byte[]? m2 = null;
        if (!meshDiag.HasErrors && !diag.HasErrors)
        {
            var ctx = new WeaponWriteContext
            {
                ModelIndex = options.ModelIndex,
                Variant = options.Variant,
                CanonicalInternalName = options.CanonicalInternalName,
                DonorM2Path = options.DonorM2Path,
                EffectTexturePaths = options.EffectTexturePaths,
            };
            m2 = _writer.WriteM2(mesh, ctx, diag);
        }

        // 4) Preview from the freshly generated bytes (§4.1).
        string? previewPath = null;
        if (m2 is not null)
        {
            var extras = new Dictionary<string, byte[]>(StringComparer.OrdinalIgnoreCase);
            if (options.EffectTexturePaths is not null)
                for (int i = 0; i < effectBlps.Count && i < options.EffectTexturePaths.Count; i++)
                    extras[options.EffectTexturePaths[i]] = effectBlps[i];
            var pr = _preview.RenderFromBytes(m2, blp, extras.Count > 0 ? extras : null);
            if (pr.Ok) previewPath = pr.GlbWebPath;
            else diag.Warn("preview.failed", pr.Error ?? "preview failed");
        }

        return new WeaponCompileOutput
        {
            M2 = m2,
            Blp = blp,
            EffectBlps = effectBlps,
            PreviewGlbWebPath = previewPath,
            Diagnostics = diag,
        };
    }

    private byte[]? EncodeTexture(WeaponTexture texture, ForgeDiagnostics diag)
    {
        try
        {
            if (texture.SourceBlp is { Length: > 0 } sourceBlp)
            {
                string? envelopeError = ValidateBlp2Envelope(sourceBlp);
                if (envelopeError is not null)
                {
                    diag.Error("blp.source", "Pre-encoded source BLP2 cannot be preserved: " + envelopeError);
                    return null;
                }

                // TBC and the supported vanilla client both consume BLP2. Keeping the original
                // bytes preserves its dimensions, mip chain, alpha encoding and DXT blocks.
                diag.Info("blp.preserved", $"Packaged source BLP2 byte-for-byte ({sourceBlp.Length:N0} bytes).");
                return sourceBlp.ToArray();
            }

            if (texture.SourcePng is not { Length: > 0 } sourcePng)
            {
                diag.Error("blp.source", "Texture has neither source BLP2 bytes nor a PNG master.");
                return null;
            }

            using var src = SKBitmap.Decode(sourcePng);
            if (src is null) { diag.Error("blp.decode", "Could not decode source texture PNG."); return null; }

            using var resized = src.Resize(new SKImageInfo(texture.Width, texture.Height), SKSamplingOptions.Default);
            if (resized is null) { diag.Error("blp.resize", $"Could not resize texture to {texture.Width}x{texture.Height}."); return null; }

            var blp = _blp.EncodeBitmapToBlp(resized, useDxt1: texture.UseDxt1);
            if (blp is null) { diag.Error("blp.encode", "BLP encoding returned null (check power-of-two dimensions)."); return null; }
            return blp;
        }
        catch (Exception ex)
        {
            diag.Error("blp.exception", $"Texture encode threw: {ex.Message}");
            return null;
        }
    }

    /// <summary>Null when <paramref name="blp"/> is a BLP2 the vanilla texture path accepts
    /// byte-for-byte; otherwise the reason. Shared with the Armor Forge's TBC importer.</summary>
    internal static string? ValidateBlp2Envelope(byte[] blp)
    {
        const int headerBytes = 148;
        const int paletteBytes = 1024;
        const int dataStart = headerBytes + paletteBytes;
        if (blp.Length < dataStart)
            return $"file is {blp.Length} bytes; a complete BLP2 header/palette requires {dataStart}";
        if (blp[0] != (byte)'B' || blp[1] != (byte)'L' || blp[2] != (byte)'P' || blp[3] != (byte)'2')
            return "magic is not BLP2";
        if (BinaryPrimitives.ReadUInt32LittleEndian(blp.AsSpan(4, 4)) != 1)
            return "JPEG/type-0 BLP2 is not supported by the vanilla texture path";

        byte encoding = blp[8], alphaDepth = blp[9], alphaType = blp[10];
        bool formatOk = encoding switch
        {
            1 => alphaDepth is 0 or 1 or 4 or 8,
            2 => (alphaType == 0 && alphaDepth is 0 or 1) ||
                 (alphaType == 1 && alphaDepth is 4 or 8) ||
                 (alphaType == 7 && alphaDepth == 8),
            3 => alphaDepth is 0 or 8,
            _ => false,
        };
        if (!formatOk)
            return $"unsupported encoding/alpha tuple {encoding}/{alphaDepth}/{alphaType}";

        uint width = BinaryPrimitives.ReadUInt32LittleEndian(blp.AsSpan(12, 4));
        uint height = BinaryPrimitives.ReadUInt32LittleEndian(blp.AsSpan(16, 4));
        static bool IsPowerOfTwo(uint value) => value != 0 && (value & (value - 1)) == 0;
        if (width == 0 || height == 0 || width > 16384 || height > 16384)
            return $"dimensions {width}x{height} are outside the supported BLP2 envelope";
        if (!IsPowerOfTwo(width) || !IsPowerOfTwo(height))
            return $"dimensions {width}x{height} violate the 1.12 compatibility policy (power-of-two required)";

        bool sawBaseMip = false;
        var mipSpans = new List<(ulong Start, ulong End, int Level)>();
        for (int level = 0; level < 16; level++)
        {
            uint offset = BinaryPrimitives.ReadUInt32LittleEndian(blp.AsSpan(20 + level * 4, 4));
            uint size = BinaryPrimitives.ReadUInt32LittleEndian(blp.AsSpan(84 + level * 4, 4));
            if (offset == 0 && size == 0) continue;
            if (offset == 0 || size == 0)
                return $"mip {level} has an incomplete offset/size pair";
            if (offset < dataStart || (ulong)offset + size > (ulong)blp.Length)
                return $"mip {level} span [{offset},{(ulong)offset + size}) is outside the file";
            ulong end = (ulong)offset + size;
            foreach (var span in mipSpans)
                if ((ulong)offset < span.End && end > span.Start)
                    return $"mip {level} overlaps mip {span.Level}";

            uint mipWidth = Math.Max(1u, width >> level);
            uint mipHeight = Math.Max(1u, height >> level);
            ulong pixels = (ulong)mipWidth * mipHeight;
            ulong minimumBytes = encoding switch
            {
                1 => pixels + (alphaDepth switch
                {
                    0 => 0UL,
                    1 => (pixels + 7) / 8,
                    4 => (pixels + 1) / 2,
                    _ => pixels,
                }),
                2 => (ulong)((mipWidth + 3) / 4) * ((mipHeight + 3) / 4) *
                     (alphaType == 0 ? 8UL : 16UL),
                3 => pixels * 4,
                _ => ulong.MaxValue,
            };
            if (size < minimumBytes)
                return $"mip {level} has {size} bytes; format requires at least {minimumBytes}";
            if (level == 0) sawBaseMip = true;
            mipSpans.Add((offset, end, level));
        }

        return sawBaseMip ? null : "base mip is absent";
    }
}

/// <summary>The mesh→M2 serialization seam. Implemented by the Phase-3 donor-scaffold writer;
/// <see cref="NullWeaponMeshWriter"/> stands in until then so the compiler produces a clear
/// diagnostic instead of failing to resolve a dependency.</summary>
public interface IWeaponMeshWriter
{
    /// <summary>Serialize a validated mesh to MD20 v256 bytes, or return null and record why.</summary>
    byte[]? WriteM2(RigidWeaponMesh mesh, WeaponWriteContext ctx, ForgeDiagnostics diag);
}

/// <summary>Context passed to the mesh writer (naming identity, etc.).</summary>
public sealed class WeaponWriteContext
{
    public required int ModelIndex { get; init; }
    public int Variant { get; init; } = 1;

    /// <summary>False keeps the donor's proven internal M2 name instead of rewriting it to
    /// SUI_W_####.mdx — a debug lever for isolating the EOF name-append in the reference client.</summary>
    public bool CanonicalInternalName { get; init; } = true;

    /// <summary>MPQ member path of the donor scaffold M2 to build on (bones, attachments,
    /// sequences follow the donor). Null → the writer's golden 1H sword.</summary>
    public string? DonorM2Path { get; init; }

    /// <summary>Packaged MPQ member paths for the mesh's effect texture slots 1.. (multi-pass
    /// glow output) — embedded as hardcoded Type-0 filenames in the emitted M2. Required when the
    /// mesh's passes reference texture slots above 0.</summary>
    public IReadOnlyList<string>? EffectTexturePaths { get; init; }
}

/// <summary>Phase-1 placeholder: the donor-scaffold M2 writer does not exist yet. Records a
/// diagnostic and returns null so the pipeline degrades cleanly rather than throwing.</summary>
public sealed class NullWeaponMeshWriter : IWeaponMeshWriter
{
    public byte[]? WriteM2(RigidWeaponMesh mesh, WeaponWriteContext ctx, ForgeDiagnostics diag)
    {
        diag.Error("m2.writer.unavailable",
            "No M2 mesh writer is registered — the Phase-3 donor-scaffold writer is not implemented yet. " +
            "Generated geometry cannot be serialized to an M2 until it lands.");
        return null;
    }
}

/// <summary>Source texture for the compiler: a PNG master plus the target BLP envelope (v1 = 128×64
/// opaque DXT1). Region masks (Route A) are carried alongside but not required.</summary>
public sealed class WeaponTexture
{
    public byte[]? SourcePng { get; init; }
    public byte[]? SourceBlp { get; init; }
    public int Width { get; init; } = 128;
    public int Height { get; init; } = 64;
    public bool UseDxt1 { get; init; } = true;
}

public sealed class WeaponCompileOptions
{
    public required int ModelIndex { get; init; }
    public int Variant { get; init; } = 1;
    public bool CanonicalInternalName { get; init; } = true;

    /// <summary>Donor scaffold M2 member for the writer (per weapon family). Null → golden sword.</summary>
    public string? DonorM2Path { get; init; }

    /// <summary>Effect textures (multi-pass glow), parallel to <see cref="EffectTexturePaths"/>.</summary>
    public IReadOnlyList<WeaponTexture>? EffectTextures { get; init; }

    /// <summary>Packaged MPQ member paths for the effect texture slots — embedded as hardcoded
    /// Type-0 filenames in the emitted M2 and added to the patch.</summary>
    public IReadOnlyList<string>? EffectTexturePaths { get; init; }

    public MeshValidationOptions MeshValidation { get; init; } = new();
}

public sealed class WeaponCompileOutput
{
    public byte[]? M2 { get; init; }
    public byte[]? Blp { get; init; }
    /// <summary>Encoded effect BLPs, parallel to the compile options' EffectTexturePaths.</summary>
    public IReadOnlyList<byte[]> EffectBlps { get; init; } = [];
    public string? PreviewGlbWebPath { get; init; }
    public required ForgeDiagnostics Diagnostics { get; init; }
    public bool Ok => M2 is not null && !Diagnostics.HasErrors;
}
