using SkiaSharp;

namespace MangosSuperUI.Services.WeaponForge;

/// <summary>
/// The pure compiler boundary (WEAPON_GEN.md §4.1): RigidWeaponMesh + WeaponTexture + options →
/// M2 bytes, BLP bytes, preview GLB, diagnostics. It has no live DB/RA/client-path dependency. The
/// mesh→M2 serialization step is delegated to <see cref="IWeaponMeshWriter"/> — absent until the
/// Phase-3 donor-scaffold writer exists, at which point it drops in without touching this class.
/// Phase 1 (the golden donor clone) does not use this compiler; it packages donor bytes directly.
/// </summary>
public sealed class WeaponAssetCompiler
{
    private readonly IWeaponMeshWriter _writer;
    private readonly BlpWriterService _blp;
    private readonly WeaponPreviewService _preview;
    private readonly ILogger<WeaponAssetCompiler> _logger;

    public WeaponAssetCompiler(IWeaponMeshWriter writer, BlpWriterService blp,
        WeaponPreviewService preview, ILogger<WeaponAssetCompiler> logger)
    {
        _writer = writer;
        _blp = blp;
        _preview = preview;
        _logger = logger;
    }

    public WeaponCompileOutput Compile(RigidWeaponMesh mesh, WeaponTexture? texture, WeaponCompileOptions options)
    {
        var diag = new ForgeDiagnostics("compile");

        // 1) Input mesh validation (§7.1).
        var meshDiag = RigidWeaponMeshValidator.Validate(mesh, options.MeshValidation);
        diag.AddRange(meshDiag);

        // 2) Texture → 128×64 DXT1 BLP (§2.4). Independent of mesh validity so a texture problem is
        //    reported even when geometry is rejected.
        byte[]? blp = null;
        if (texture is not null)
            blp = EncodeTexture(texture, diag);

        // 3) Mesh → M2, only if the mesh passed and a writer is available.
        byte[]? m2 = null;
        if (!meshDiag.HasErrors)
        {
            var ctx = new WeaponWriteContext
            {
                ModelIndex = options.ModelIndex,
                Variant = options.Variant,
                CanonicalInternalName = options.CanonicalInternalName,
            };
            m2 = _writer.WriteM2(mesh, ctx, diag);
        }

        // 4) Preview from the freshly generated bytes (§4.1).
        string? previewPath = null;
        if (m2 is not null)
        {
            var pr = _preview.RenderFromBytes(m2, blp);
            if (pr.Ok) previewPath = pr.GlbWebPath;
            else diag.Warn("preview.failed", pr.Error ?? "preview failed");
        }

        return new WeaponCompileOutput
        {
            M2 = m2,
            Blp = blp,
            PreviewGlbWebPath = previewPath,
            Diagnostics = diag,
        };
    }

    private byte[]? EncodeTexture(WeaponTexture texture, ForgeDiagnostics diag)
    {
        try
        {
            using var src = SKBitmap.Decode(texture.SourcePng);
            if (src is null) { diag.Error("blp.decode", "Could not decode source texture PNG."); return null; }

            using var resized = src.Resize(new SKImageInfo(texture.Width, texture.Height), SKSamplingOptions.Default);
            if (resized is null) { diag.Error("blp.resize", $"Could not resize texture to {texture.Width}x{texture.Height}."); return null; }

            var blp = _blp.EncodeBitmapToBlp(resized, useDxt1: texture.UseDxt1);
            if (blp is null) { diag.Error("blp.encode", "BLP encoding returned null (check power-of-two dimensions)."); return null; }
            return blp;
        }
        catch (Exception ex)
        {
            diag.Error("blp.exception", $"Texture encode threw: {ex.Message}");
            return null;
        }
    }
}

/// <summary>The mesh→M2 serialization seam. Implemented by the Phase-3 donor-scaffold writer;
/// <see cref="NullWeaponMeshWriter"/> stands in until then so the compiler produces a clear
/// diagnostic instead of failing to resolve a dependency.</summary>
public interface IWeaponMeshWriter
{
    /// <summary>Serialize a validated mesh to MD20 v256 bytes, or return null and record why.</summary>
    byte[]? WriteM2(RigidWeaponMesh mesh, WeaponWriteContext ctx, ForgeDiagnostics diag);
}

/// <summary>Context passed to the mesh writer (naming identity, etc.).</summary>
public sealed class WeaponWriteContext
{
    public required int ModelIndex { get; init; }
    public int Variant { get; init; } = 1;

    /// <summary>False keeps the donor's proven internal M2 name instead of rewriting it to
    /// SUI_W_####.mdx — a debug lever for isolating the EOF name-append in the reference client.</summary>
    public bool CanonicalInternalName { get; init; } = true;
}

/// <summary>Phase-1 placeholder: the donor-scaffold M2 writer does not exist yet. Records a
/// diagnostic and returns null so the pipeline degrades cleanly rather than throwing.</summary>
public sealed class NullWeaponMeshWriter : IWeaponMeshWriter
{
    public byte[]? WriteM2(RigidWeaponMesh mesh, WeaponWriteContext ctx, ForgeDiagnostics diag)
    {
        diag.Error("m2.writer.unavailable",
            "No M2 mesh writer is registered — the Phase-3 donor-scaffold writer is not implemented yet. " +
            "Generated geometry cannot be serialized to an M2 until it lands.");
        return null;
    }
}

/// <summary>Source texture for the compiler: a PNG master plus the target BLP envelope (v1 = 128×64
/// opaque DXT1). Region masks (Route A) are carried alongside but not required.</summary>
public sealed class WeaponTexture
{
    public required byte[] SourcePng { get; init; }
    public int Width { get; init; } = 128;
    public int Height { get; init; } = 64;
    public bool UseDxt1 { get; init; } = true;
}

public sealed class WeaponCompileOptions
{
    public required int ModelIndex { get; init; }
    public int Variant { get; init; } = 1;
    public bool CanonicalInternalName { get; init; } = true;
    public MeshValidationOptions MeshValidation { get; init; } = new();
}

public sealed class WeaponCompileOutput
{
    public byte[]? M2 { get; init; }
    public byte[]? Blp { get; init; }
    public string? PreviewGlbWebPath { get; init; }
    public required ForgeDiagnostics Diagnostics { get; init; }
    public bool Ok => M2 is not null && !Diagnostics.HasErrors;
}
